# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comentarios_pb2 as comentarios__pb2


class Comentarios1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarComentario = channel.unary_unary(
                '/Comentarios1/AgregarComentario',
                request_serializer=comentarios__pb2.Comentarios.SerializeToString,
                response_deserializer=comentarios__pb2.Va.FromString,
                )
        self.TraerComentariosPorIdReceta = channel.unary_stream(
                '/Comentarios1/TraerComentariosPorIdReceta',
                request_serializer=comentarios__pb2.Rid.SerializeToString,
                response_deserializer=comentarios__pb2.Comentarios.FromString,
                )


class Comentarios1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarComentario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerComentariosPorIdReceta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Comentarios1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarComentario': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarComentario,
                    request_deserializer=comentarios__pb2.Comentarios.FromString,
                    response_serializer=comentarios__pb2.Va.SerializeToString,
            ),
            'TraerComentariosPorIdReceta': grpc.unary_stream_rpc_method_handler(
                    servicer.TraerComentariosPorIdReceta,
                    request_deserializer=comentarios__pb2.Rid.FromString,
                    response_serializer=comentarios__pb2.Comentarios.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Comentarios1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comentarios1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarComentario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Comentarios1/AgregarComentario',
            comentarios__pb2.Comentarios.SerializeToString,
            comentarios__pb2.Va.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TraerComentariosPorIdReceta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Comentarios1/TraerComentariosPorIdReceta',
            comentarios__pb2.Rid.SerializeToString,
            comentarios__pb2.Comentarios.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
