# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comentarios.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omentarios.proto\"^\n\x0b\x43omentarios\x12\x15\n\ridcomentarios\x18\x01 \x01(\x05\x12\r\n\x05recet\x18\x02 \x01(\x05\x12\x15\n\rusuario_comen\x18\x03 \x01(\t\x12\x12\n\ncomentario\x18\x04 \x01(\t\"\x04\n\x02Va26\n\x0c\x43omentarios1\x12&\n\x11\x41gregarComentario\x12\x0c.Comentarios\x1a\x03.Vab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comentarios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMENTARIOS']._serialized_start=21
  _globals['_COMENTARIOS']._serialized_end=115
  _globals['_VA']._serialized_start=117
  _globals['_VA']._serialized_end=121
  _globals['_COMENTARIOS1']._serialized_start=123
  _globals['_COMENTARIOS1']._serialized_end=177
# @@protoc_insertion_point(module_scope)
