# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recetafavoritas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recetafavoritas.proto\"d\n\x0fRecetaFavoritas\x12\x19\n\x11idrecetaFavoritas\x18\x01 \x01(\x05\x12\x1b\n\x13recetasFavoritascol\x18\x02 \x01(\t\x12\x19\n\x11usuario_idusuario\x18\x03 \x01(\x05\"\x07\n\x05Nulos29\n\tRecetaFav\x12,\n\x10\x41gregarRecetaFav\x12\x10.RecetaFavoritas\x1a\x06.Nulosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recetafavoritas_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECETAFAVORITAS']._serialized_start=25
  _globals['_RECETAFAVORITAS']._serialized_end=125
  _globals['_NULOS']._serialized_start=127
  _globals['_NULOS']._serialized_end=134
  _globals['_RECETAFAV']._serialized_start=136
  _globals['_RECETAFAV']._serialized_end=193
# @@protoc_insertion_point(module_scope)
