# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recetafavoritas_pb2 as recetafavoritas__pb2


class RecetaFavStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarRecetaFav = channel.unary_unary(
                '/RecetaFav/AgregarRecetaFav',
                request_serializer=recetafavoritas__pb2.RecetaFavoritas.SerializeToString,
                response_deserializer=recetafavoritas__pb2.Nulos.FromString,
                )


class RecetaFavServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarRecetaFav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecetaFavServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarRecetaFav': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarRecetaFav,
                    request_deserializer=recetafavoritas__pb2.RecetaFavoritas.FromString,
                    response_serializer=recetafavoritas__pb2.Nulos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecetaFav', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecetaFav(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarRecetaFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecetaFav/AgregarRecetaFav',
            recetafavoritas__pb2.RecetaFavoritas.SerializeToString,
            recetafavoritas__pb2.Nulos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
