# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suscripcion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suscripcion.proto\"L\n\x0bSuscripcion\x12\x15\n\ridsuscripcion\x18\x01 \x01(\x05\x12\x15\n\rfollowed_user\x18\x02 \x01(\t\x12\x0f\n\x07my_user\x18\x03 \x01(\t\"\x07\n\x05Vacio\"\x10\n\x03seg\x12\t\n\x01s\x18\x01 \x01(\t28\n\rSuscripciones\x12\'\n\x0fTraerSeguidores\x12\x04.seg\x1a\x0c.Suscripcion0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suscripcion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUSCRIPCION']._serialized_start=21
  _globals['_SUSCRIPCION']._serialized_end=97
  _globals['_VACIO']._serialized_start=99
  _globals['_VACIO']._serialized_end=106
  _globals['_SEG']._serialized_start=108
  _globals['_SEG']._serialized_end=124
  _globals['_SUSCRIPCIONES']._serialized_start=126
  _globals['_SUSCRIPCIONES']._serialized_end=182
# @@protoc_insertion_point(module_scope)
