# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suscripcion_pb2 as suscripcion__pb2


class SuscripcionesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TraerSeguidores = channel.unary_stream(
                '/Suscripciones/TraerSeguidores',
                request_serializer=suscripcion__pb2.seg.SerializeToString,
                response_deserializer=suscripcion__pb2.Suscripcion.FromString,
                )


class SuscripcionesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TraerSeguidores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuscripcionesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TraerSeguidores': grpc.unary_stream_rpc_method_handler(
                    servicer.TraerSeguidores,
                    request_deserializer=suscripcion__pb2.seg.FromString,
                    response_serializer=suscripcion__pb2.Suscripcion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Suscripciones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Suscripciones(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TraerSeguidores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Suscripciones/TraerSeguidores',
            suscripcion__pb2.seg.SerializeToString,
            suscripcion__pb2.Suscripcion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
